// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuXngkk3jmE_ywu-pT4VAqDzLQ_whWVcU',
    appId: '1:913061584547:web:2d7572c6780f07b3e8e916',
    messagingSenderId: '913061584547',
    projectId: 'reminder-app-5d832',
    authDomain: 'reminder-app-5d832.firebaseapp.com',
    storageBucket: 'reminder-app-5d832.appspot.com',
    measurementId: 'G-RQ0JBYWC48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXYRS-ZFZtUMEBdhEahWhUA9KL1pvE4q0',
    appId: '1:913061584547:android:2df750dfb33aaf5ae8e916',
    messagingSenderId: '913061584547',
    projectId: 'reminder-app-5d832',
    storageBucket: 'reminder-app-5d832.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCK5BkQJFhE1eR7Jd9bR7Om7ORoapdroQ',
    appId: '1:913061584547:ios:51d9ca325a46348ee8e916',
    messagingSenderId: '913061584547',
    projectId: 'reminder-app-5d832',
    storageBucket: 'reminder-app-5d832.appspot.com',
    iosBundleId: 'com.example.alertmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCK5BkQJFhE1eR7Jd9bR7Om7ORoapdroQ',
    appId: '1:913061584547:ios:cb308e486d4732fce8e916',
    messagingSenderId: '913061584547',
    projectId: 'reminder-app-5d832',
    storageBucket: 'reminder-app-5d832.appspot.com',
    iosBundleId: 'com.example.alertmate.RunnerTests',
  );
}
